markdown: kramdown
production: true
gems:
    - jekyll-sitemap
    - jekyll-redirect-from
exclude:
  - vendor
  - README.md
  - Makefile
  - Gemfile
  - Gemfile.lock
  - CHANGELOG.md
  - .travis.yml

theme: jekyll-theme-cayman